//Salons
export const FETCH_SALONS_START = "FETCH_SALONS_START";
export const FETCH_SALONS_SUCCESS = "FETCH_SALONS_SUCCESS";
export const FETCH_SALONS_FAIL = "FETCH_SALONS_FAIL";

export const CREATE_SALON_START = "CREATE_SALON_START";
export const CREATE_SALON_SUCCESS = "CREATE_SALON_SUCCESS";
export const CREATE_SALON_FAIL = "CREATE_SALON_FAIL";

export const UPDATE_SALON_START = "UPDATE_SALON_START";
export const UPDATE_SALON_SUCCESS = "UPDATE_SALON_SUCCESS";
export const UPDATE_SALON_FAIL = "UPDATE_SALON_FAIL";

export const DELETE_SALON_START = "DELETE_SALON_START";
export const DELETE_SALON_SUCCESS = "DELETE_SALON_SUCCESS";
export const DELETE_SALON_FAIL = "DELETE_SALON_FAIL";

export const RESET_DATA_AFTER_ACTION = "RESET_DATA_AFTER_ACTION";
