//Salons
export const FETCH_SALONS_START = "FETCH_SALONS_START";
export const FETCH_SALONS_SUCCESS = "FETCH_SALONS_SUCCESS";
export const FETCH_SALONS_FAIL = "FETCH_SALONS_FAIL";

export const CREATE_SALON_START = "CREATE_SALON_START";
export const CREATE_SALON_SUCCESS = "CREATE_SALON_SUCCESS";
export const CREATE_SALON_FAIL = "CREATE_SALON_FAIL";

export const UPDATE_SALON_START = "UPDATE_SALON_START";
export const UPDATE_SALON_SUCCESS = "UPDATE_SALON_SUCCESS";
export const UPDATE_SALON_FAIL = "UPDATE_SALON_FAIL";

export const DELETE_SALON_START = "DELETE_SALON_START";
export const DELETE_SALON_SUCCESS = "DELETE_SALON_SUCCESS";
export const DELETE_SALON_FAIL = "DELETE_SALON_FAIL";

//locations
export const FETCH_LOCATIONS_START = "FETCH_LOCATIONS_START";
export const FETCH_LOCATIONS_SUCCESS = "FETCH_LOCATIONS_SUCCESS";
export const FETCH_LOCATIONS_FAIL = "FETCH_LOCATIONS_FAIL";

export const CREATE_LOCATION_START = "CREATE_LOCATION_START";
export const CREATE_LOCATION_SUCCESS = "CREATE_LOCATION_SUCCESS";
export const CREATE_LOCATION_FAIL = "CREATE_LOCATION_FAIL";

export const UPDATE_LOCATION_START = "UPDATE_LOCATION_START";
export const UPDATE_LOCATION_SUCCESS = "UPDATE_LOCATION_SUCCESS";
export const UPDATE_LOCATION_FAIL = "UPDATE_LOCATION_FAIL";

export const DELETE_LOCATION_START = "DELETE_LOCATION_START";
export const DELETE_LOCATION_SUCCESS = "DELETE_LOCATION_SUCCESS";
export const DELETE_LOCATION_FAIL = "DELETE_LOCATION_FAIL";

//Services
export const FETCH_SERVICES_START = "FETCH_SERVICES_START";
export const FETCH_SERVICES_SUCCESS = "FETCH_SERVICES_SUCCESS";
export const FETCH_SERVICES_FAIL = "FETCH_SERVICES_FAIL";

export const CREATE_SERVICE_START = "CREATE_SERVICE_START";
export const CREATE_SERVICE_SUCCESS = "CREATE_SERVICE_SUCCESS";
export const CREATE_SERVICE_FAIL = "CREATE_SERVICE_FAIL";

export const UPDATE_SERVICE_START = "UPDATE_SERVICE_START";
export const UPDATE_SERVICE_SUCCESS = "UPDATE_SERVICE_SUCCESS";
export const UPDATE_SERVICE_FAIL = "UPDATE_SERVICE_FAIL";

export const DELETE_SERVICE_START = "DELETE_SERVICE_START";
export const DELETE_SERVICE_SUCCESS = "DELETE_SERVICE_SUCCESS";
export const DELETE_SERVICE_FAIL = "DELETE_SERVICE_FAIL";

//Masters
export const FETCH_MASTERS_START = "FETCH_MASTERS_START";
export const FETCH_MASTERS_SUCCESS = "FETCH_MASTERS_SUCCESS";
export const FETCH_MASTERS_FAIL = "FETCH_MASTERS_FAIL";

export const CREATE_MASTER_START = "CREATE_MASTER_START";
export const CREATE_MASTER_SUCCESS = "CREATE_MASTER_SUCCESS";
export const CREATE_MASTER_FAIL = "CREATE_MASTER_FAIL";

export const UPDATE_MASTER_START = "UPDATE_MASTER_START";
export const UPDATE_MASTER_SUCCESS = "UPDATE_MASTER_SUCCESS";
export const UPDATE_MASTER_FAIL = "UPDATE_MASTER_FAIL";

export const DELETE_MASTER_START = "DELETE_MASTER_START";
export const DELETE_MASTER_SUCCESS = "DELETE_MASTER_SUCCESS";
export const DELETE_MASTER_FAIL = "DELETE_MASTER_FAIL";

export const RESET_DATA_AFTER_ACTION = "RESET_DATA_AFTER_ACTION";

//Reservations
export const FETCH_RESERVATIONS_START = "FETCH_RESERVATIONS_START";
export const FETCH_RESERVATIONS_SUCCESS = "FETCH_RESERVATIONS_SUCCESS";
export const FETCH_RESERVATIONS_FAIL = "FETCH_RESERVATIONS_FAIL";

//Clients
export const FETCH_CLIENTS_START = "FETCH_CLIENTS_START";
export const FETCH_CLIENTS_SUCCESS = "FETCH_CLIENTS_SUCCESS";
export const FETCH_CLIENTS_FAIL = "FETCH_CLIENTS_FAIL";
